spring:
  datasource:
    url: jdbc:mysql://localhost:3306/purchaseApiDB?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: create

app:
  jwt:
    apiSecretKey: purchaseListApi
    tokenValidity: 7200000