spring:
  datasource:
    url: jdbc:mysql://localhost:3306/purchaseApiDB?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: create

app:
  jwt:
    secureKeyAlgorithm: HmacSHA512
    secureKeyBitLength: 512
    tokenValidity: 7200000