spring:
  datasource:
    url: jdbc:mysql://localhost:3306/purchaseApiDB?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

app:
  jwt:
    secureKeyAlgorithm: HmacSHA512
    secureKeyBitLength: 512
    tokenValidity: 7200000
    apiSecretKey: ApiSecretKeyVeryLongAndBoringWord26846132